[package]
name = "sai_upgrade"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
repository.workspace = true

[dependencies]
starknet.workspace = true
sai_access = { path = "../access" }

[dev-dependencies]

[tool]
fmt.workspace = true
scarb.workspace = true

[lib]
