[package]
name = "sai_token"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
experimental-features = ["associated_item_constraints"]


[tool]
fmt.workspace = true
scarb.workspace = true

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[dev-dependencies]
# dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }

[lib]
