[workspace.package]
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.11.4"
scarb-version = "2.11.4"
repository = "https://github.com/sai-starknet/cairo-utils"

[workspace]
members = [
    "packages/access",
    "packages/token",
    "packages/upgrade",
    "packages/core",
    "packages/emit_return",
    "packages/packing",
    "packages/address",
]

[workspace.dependencies]
starknet = "2.11.4"
openzeppelin_introspection = "2.0.0"
openzeppelin_token = "2.0.0"

[workspace.dev-dependencies]
cairo_test = "2.11.4"

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[package]
name = "sai_utils"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true

[dependencies]
starknet.workspace = true
sai_access = { path = "packages/access" }
sai_token = { path = "packages/token" }
sai_upgrade = { path = "packages/upgrade" }
sai_core_utils = { path = "packages/core" }
sai_return = { path = "packages/emit_return" }
sai_packing = { path = "packages/packing" }

[dev-dependencies]
cairo_test = "2.11.4"

[lib]

[tool]
fmt.workspace = true
scarb.workspace = true

[[target.starknet-contract]]
sierra = true
casm = false
