[package]
name = "sai_return"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
repository.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]

[tool]
fmt.workspace = true
scarb.workspace = true

[lib]
