pub mod byte;
pub mod consts;
pub mod int;
mod shift;
pub use byte::{BytePacking, MaskDowncast};
pub use consts::{masks, neg_bits, shifts};
pub use int::IntPacking;
pub use masks::*;
pub use neg_bits::*;
pub use shift::{BShiftCast, GetShift, ShiftCast};
pub use shifts::*;
